#!/bin/sh

echo 'Downloading thoughtbot/laptop....'

cd $HOME
curl --remote-name https://raw.githubusercontent.com/thoughtbot/laptop/master/mac

if [ ! -L "$HOME/.laptop.local" ]; then
    echo "Symlinking .laptop.local..."
    ln -s  "$HOME/dotfiles/laptop.local" "$HOME/.laptop.local"
else
    echo ".laptop.local already linked..."
fi

echo 'Running `sh mac 2>&1 | tee ~/laptop.log`...'

sh mac 2>&1 | tee ~/laptop.log

# instal omtmux
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
# install ohmyzsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# install space-vim
bash <(curl -fsSL https://raw.githubusercontent.com/liuchengxu/space-vim/master/install.sh)

echo 'linking rc files'
rcup -f

# Great Git Defaults
git config --global pull.rebase true
git config --global fetch.prune true
git config --global diff.colorMoved zebra
